version: '3.8'

services:
  aggregator:
    build:
      context: ./server/aggregator
    env_file:
      - .env
    environment:
      - RPC_URL=http://hardhat:8545
      - REGISTRY_ADDR=0x...
    restart: always

  fetcher-1:
    build:
      context: ./server/ingestion
    environment:
      - NODE_ID=1
      - PRIVATE_KEY=0x...
    restart: always

  fetcher-2:
    build:
      context: ./server/ingestion
    environment:
      - NODE_ID=2
      - PRIVATE_KEY=0x...
    restart: always

  fetcher-3:
    build:
      context: ./server/ingestion
    environment:
      - NODE_ID=3
      - PRIVATE_KEY=0x...
    restart: always
